export const PRODUCTS = [
  {
    id: 1,
    category: 1,
    name: 'Harina blanca',
    description: 'Harina blanca para pan',
    weight: '1/2 kg',
    price: 10,
  },
  {
    id: 2,
    category: 1,
    name: 'Harina de almendras',
    description: 'Harina de almendras para pan',
    weight: '1/2 kg',
    price: 10,
  },
  {
    id: 3,
    category: 2,
    name: 'Levadura fresca',
    description: 'levadura fresca para tu pan',
    weight: '1/2 kg',
    price: 10,
  },
  {
    id: 4,
    category: 2,
    name: 'Levadura seca',
    description: 'levadura seca para tu pan',
    weight: '1/2 kg',
    price: 10,
  },
  {
    id: 5,
    category: 3,
    name: 'Aceite de oliva virgen',
    description: 'Aceite de oliva virgen para preparar tu pan',
    weight: '1/2 kg',
    price: 10,
  },
  {
    id: 6,
    category: 3,
    name: 'Aceite de oliva extra virgen',
    description: 'Aceite de oliva extra virgen para preparar tu pan',
    weight: '1/2 kg',
    price: 10,
  },
  {
    id: 7,
    category: 4,
    name: 'Baguette blanco',
    description: 'Rico pan baguette',
    weight: '1/2 kg',
    price: 10,
  },
  {
    id: 8,
    category: 4,
    name: 'Baguette integral',
    description: 'Rico pan baguette integral',
    weight: '1/2 kg',
    price: 10,
  },
  {
    id: 9,
    category: 5,
    name: 'Pan de aceituna negra',
    description: 'pan de aceituna negra',
    weight: '1/2 kg',
    price: 10,
  },
  {
    id: 10,
    category: 5,
    name: 'Pan de aceituna verde',
    description: 'pan de aceituna verde',
    weight: '1/2 kg',
    price: 10,
  },
  {
    id: 11,
    category: 6,
    name: 'Pan masa madre blanco',
    description: 'Pan blanco de masa madre',
    weight: '1/2 kg',
    price: 10,
  },
  {
    id: 12,
    category: 6,
    name: 'Pan masa madre integral',
    description: 'Pan integral de masa madre',
    weight: '1/2 kg',
    price: 10,
  },
  {
    id: 11,
    category: 7,
    name: 'Pan de molde blanco',
    description: 'Pan de molde artesanal blanco',
    weight: '1/2 kg',
    price: 10,
  },
  {
    id: 12,
    category: 7,
    name: 'Pan de molde integral',
    description: 'Pan de molde artesanal integral',
    weight: '1/2 kg',
    price: 10,
  },
];
